# We use conda so we can also install bedtools.

language: python
dist: xenial

python:
  - "3.7"

services:
  - docker

install:
  - sudo apt update && sudo apt install bedtools
  - pip install tox

script:
  - tox