# We use conda so we can also install bedtools.

language: python

env:
  - PY_VERSION="3.7"

services:
  - docker

before_install:
  # Install conda
  - export MINICONDA=${HOME}/miniconda
  - export PATH=${MINICONDA}/bin:${PATH}
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -f -p ${MINICONDA}
  - conda config --set always_yes yes
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge

install:
  - conda install python=${PY_VERSION} tox bedtools

script:
  - tox